// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadTaskProcessStatus } from "./ThreadTaskProcessStatus";

export type ThreadTaskProcess = {
/**
 * Stable identifier assigned by the runtime, not an operating-system PID.
 */
processId: string, itemId: string,
/**
 * Fixed runtime classification `unified-exec`, never a command-derived name.
 */
executable: string,
/**
 * Live when sampled; the process may exit before the response arrives.
 */
status: ThreadTaskProcessStatus, };
